# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'Gemfile', 'Gemfile.lock']


# Site Settings
title: "DevOps China Summit"
email: "info@devopsmeetup.com"
description: "中国DevOps社区年会官网"
baseurl: ""
url: "https://conf.devopsmeetup.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-159133967-1"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "DevOps China"
organizerAlternateName: "DevOps China"
organizerDescription: "开放和志愿者共建的社区，交流、分享和传播DevOps的理念/实践，心怀建设更好社区的激情。"
organizerEmail: "info@devopschina.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://DevOpsChina.org"

# Head
metaKeywords: "china, devops, sre, community, programming, cd, ci, itil, agile"
twitterAccount: "@devops_meetup"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "首页"}
 - {permalink: "/blog/", text: "新闻"}
 - {permalink: "/schedule/", text: "日程"}
 - {permalink: "/speakers/", text: "讲师"}
 - {permalink: "/team/", text: "团队"}
 - {permalink: "/logistics/", text: "场地"}
 #- {permalink: "/hackathon/", text: "培训"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "讲师招募"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "赞助大会"}

# Hero Block
heroImage: "hero1.jpg"
heroTitle: "DevOps China <typeout> 2020"
eventDate: "September - 18th, 2020"
typeoutTextValues: '"Summit", "社区", "峰会", "大连"'
typeoutFallback: "大连"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "讲师招募"}
 - {permalink: "/#tickets", text: "购票"}

# About Block
aboutTitle: "中国DevOps社区峰会"
aboutBlock:
 - {title: "社区大会", image: "conference.jpg", text: "DevOps社区的年度最大盛会，技术交流的嘉年华，参与者都是社区的一份子！同聚一堂汲取社区营养，感受成长和分享的喜悦！" }
 - {title: "工作坊", image: "workshop.jpg", text: "全天或半天的工作坊，上手实践练习，各种浓缩的理论和实践学习。和你喜爱的讲师一起沉浸在社区中!" }
 - {title: "社区互动", image: "hackathon.jpg", text: "社区组织者和志愿者专属活动区，年度工作经验交流和分享，每个人都是社区构建者，内部认证培训征集中!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "550", specialCharacter: "+", info: "参会者", detail: "来自全国各地"}
 - {count: "48", specialCharacter: "+", info: "小时", detail: "纯粹DevOps技术"}
 - {count: "20", specialCharacter: "+", info: "演讲", detail: "国内外分享嘉宾"}
 - {count: "50", specialCharacter: "+", info: "志愿者", detail: "社区组织者和志愿者"}

# Latest News Block
latestNewsTitle: "最新动态"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "高人气讲师"
rockstarSpeakersButtonText: "查看讲师团"

# Location Block
locationBlockTitle: "地点"
eventLocationName: "主会场"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "xyz街100号"
eventAddressLocality: "abc酒店"
eventAddressLocalityRegion: "abc区"
eventPostalCode: "79000"
eventAddressCountry: "中国"
eventStartTime: "2020-09-18T10:00"
eventDoorTime: "09:00"
eventEndTime: "2020-09-19T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "分会场"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "宏伟的主会场"
venueFeatures: ["3 三个庞大的液晶显示屏", "杜比环绕立体声系统", "靠近市中心交通便利"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "跟踪最新消息?"
twitterHashTag: "微信号DevOpsMeetup"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "组织者"
partnersTitle: "合作伙伴"
partnersC4sponsorsButton: "赞助大会"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "订阅更新"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "门票将于2020年5月份开放注册，某些票种数量有限，紧随最新消息更新！"

# Tickets Block
ticketsTitle: "票价"
ticketsInfo: "票价含大会当天的所有会议日程。午餐和住宿不包含在票价之内。"
ticketsOffers:
 -
  name: "早鸟票"
  price: "350"
  priceCurrency: "人民币"
  ticketsNumber: "350"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "现在注册"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2020-08-25T10:00"
  validThrough: "2020-09-30T23:59"
 -
  name: "正常票"
  price: "800"
  priceCurrency: "人民币"
  ticketsNumber: "800"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "现在注册"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2020-10-01T00:00"
  validThrough: "2020-10-23T23:59"
  disabled: true
 -
  name: "学生"
  price: "100"
  priceCurrency: "人民币"
  ticketsNumber: "100"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "现在注册"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/DevOpsCN", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "linkedin"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "链接"
  links:
   - {link: "https//devopschina.org", text: "社区官网"}
   - {link: "https://forum.devopsmeetup.com", text: "社区论坛"}
 -
  title: "联系方式"
  links:
   - {link: "mailto:info@devopschina.org", text: "info@devopschina.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "最新动态"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "关于我们"
aboutUs: "中国DevOps社区萌芽于2017年，2018年7月22日正式成立，在不同的城市由社区志愿者自发组织，全国志愿者人数超过450人，同时我们有15位理事会成员，统筹和监管专职运营团队开展全国社区的运营。我们社区的核心定位是：传播DevOps的文化、理念和实践，提供一个开放、平等的分享平台，服务于广大的DevOps实践者。"

# Logistics Find Way Block
findWayTitle: "主会场在这里"
findWayDistance: "距离"
findWayDriving: "开车"
findWayWalking: "步行"
findWayBicycling: "自行车"
findWayTransit: "地铁"
findWayFindFlight: "航班"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "会场周边"
directionDetailsCards:
 - {title: "从机场前来", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "公共交通", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "酒店", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "问题?"
  subCards:
   -
    title: "酒店"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "注册"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "参会者信息"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
